services:
  app:
    build:
        context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/onecraft
      - SPRING_DATASOURCE_USERNAME=onecraft
      - SPRING_DATASOURCE_PASSWORD=onecraft
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=onecraft
      - POSTGRES_USER=onecraft
      - POSTGRES_PASSWORD=onecraft